spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets_db
    username: tickets_user
    password: 1234567@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/event-ticket-platform

logging:
  level:
    org.hibernate.SQL: DEBUG